name: Run Scala Package Release

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: main

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set Github User
        run: |
          git config --local user.email "dataeng@audiense.com"
          git config --local user.name "GitHub Action DataEng"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      #        git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
      - name: Compile
        run: sbt +compile
      - name: Release
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} sbt -v "release cross with-defaults"
      - name: Push new version
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} git push origin main